### ISSUE TITLE
Create Job Summary endpoint

### ISSUE THREAD

**Issue by shairozan** [metrumresearchgroup/chokhmah#3]
There are cases in which thousands and thousands of jobs may be submitted, so polling would not be sane in an event where the response could be that large or take that long to present. So it would make sense to provide a summary endpoint that lists

```
Pending:
 Total: xxx
 Start: 204
 End: 52405
Running:
 Total: xxx
 Start: 100
 End: 203

```
